export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT = "LOGOUT";
export const GET_EXPERTS_DATA = "GET_EXPERTS_DATA";
export const APPROVE_PENDING_REQUEST = "APPROVE_PENDING_REQUEST";
export const ADD_NOTES = "ADD_NOTES";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const GET_TEMPLATE = "GET_TEMPLATE";

export const GET_VERIFICATION_LIST = "GET_VERIFICATION_LIST";

export const GET_MEMBERS_DATA = "GET_MEMBERS_DATA";

export const CLEAR_STORE = "CLEAR_STORE";

export const TEST = "TEST";
